language: java

#Using the default oracleJdk8 proposed by Travis
jdk:
  - oraclejdk8

#We don't need to retrieve all the commits
git:
  depth: 3

#Define here the host and ip of the stage environment
#Secure keys are for SONAR_TOKEN, TOMCAT_MANAGER_LOGIN and TOMCAT_MANAGER_PASSWORD
env:
  global:
    - STAGE_HOST=clickp.stage.env
    - STAGE_IP=88.171.128.121
    - secure: qrWqvYUSe2rHmv1Q3EMP92F6x035TYgWwYFxfHEXOZItV6Fjm/RXpjXJ8HZQrWDxCKfcgC0mVEfecdmy7z1GLwEDxMMUi3l/wFOqXL81MIGkzZNKxNuLpbYzSNcRPDELqPQ2vFgrva8b/OpmS2nsk8MmtVd/LEW9pf+gAJoeh7Ady6mbzHgrH3IwXwTBTmVHvKHqim5G4Q1u/Ba+sSSl74LvdLhzXfL+IKTa62+dgLuHoGk3+XPWV9z1vQK2CbEeba/oI+FUlasIPHYNQPTYwnm5H4ZoE14ljt+rOabPaw3CWrvICB0meFRzOcok3kfRYuLj1YSp1gCwhblmVUGh1d5qdRqRTlwZgsf0DlAPvI7YreOh/5g6/4ji4eQVryIAnAYx21TDMMTMHdmy4BGAuetzSYTRDoX3UyZsEkP0XM/zOFewIECltB0RsFosoBA7KMXtMAHnkbxvGcAbzExEgXJQ986hfnkPq3jLuRBFnIOoK3C4b1yEAK6X2v117YUZTQCraA7CFL4ae2eUVqWFOBWHRxyuDxtmvzSahPtAviE57sCJnPX8wDbjNvX0WQQSLYfTxXQH7GO1wFZxsEaZPVonjHyr1/eNpn3Z+tJwthsDccvsPfz54bVSfbdr27SXeq/ngjuKqIJc6zYn5pGoTKreDqzBEpEMyHsqRqVH7F8=
    - secure: nEHBsT6/gZpwCsApOMv9lo3aOtw2zZryPNZYL84Ye0j0cvLkXCMUoZbUl5f8ZrslrsZayAJ8LDWPkBO5PJ7BBS5YkO05xBEGmw4Ct2bF5IN00LgaDazBslGSAP9hD4cvBk/MJgAhJwKZtTOXOHXBFXuJ+RZEl7OEdhvmrKtmkrO8r3VrGV988jbL4Zaf3VP8ErjRL31xBp3tjybrgPbMZmKRMqxjTeCfBnt+vIAxnLZT2YWH/UfVzDiUT/MnJSdFmQGEkM60dXev3IuQO02WeI1dwF2WUFIM22tUznogFQGOzgNNos1ICRYd3EB63RAIvxmRqVkIEhicZvKqHAzlZLzns5DBugQaAlFjCys2Is6BTyidPtDyWQpkOs5cYXM5cQNQdRrfKm4hcQEUEzSCcr86VjdSP1Ch4JANnQeZ1ouOtHT81AVAjZneb0ADuzchWg9Mcfv0QTfcfY6ohzbDBW9cM713XSd42GkStd6POX50BprEW9dOOv+Ue0zZ9H//OvUCWXjnbZihRs/4fTo25uniDI8sdyBt7o//ELxHalv3glbJZqgnRJ8B1og+B0OLuXuBXMivGfNDGEpQCiBKUC2NUAU3CdxvzrUj7rc+zaM+zrITXbt/vUSFpYbE1cqIxSzeO/luZ5ZWJd+NDWh1gH5Cf2ziOKiPsyel+mkG6RM=    
    - secure: CfoKqLb58dGSj0Tm4QJ6iGB2YqvpQfw9tFxDbf3CA8J2aVw2ghFdVnSRs2qWfbe3ZhH82821b5wclkHMvYMltOL4xGOzz1FrbUa1gfoboFF29R/0VtL6V8NuSiX4ficjqZJ2UkTINE8RQi0KnkjtcPOB4Htyo068X8F3LHWQBOu3uKD18xGhwRg52pS0S+tEzXwCi/owK4Hn/4iWO6+79z0VoVW+yNUoVdbrVGVhtqhPvVStySkZzCwtWffl7IQSXGMfpmKdSSQkaBz8DxGr8MqoM+q7pxAakAXgR2A2QSvWz9KwL0Tdzu0vvNt+zhR/VazUZ5p16PE/Wr9Lc9CHWeFRM3Kie6V2/rdv4o0Qf7C0G0vTm1pYEAaxMpR2jWE+EcW8/v6n4JZqpVFhQRu0aRRW1L5qxuaAZG+rTCQt43owzIA8tLy92PdbbrHIotqeXo5VWhI4LjGxzCqt3ywAAu0vVegFv9sjnRpknV6ePLe9aGVVkdXt/ChfCij7s23V3ZC/NYQNJHfxsJsFgJVCY8ttN8Cagtk7eI+O9aSRmPdyMy5yILkw75uA9V5zK/V0b/cE5ITutoV1/ozJn91YQ9QqrZg85ldkFkP6tJ2MK6wu6TSosYhlxtSFWQtUO/q5Q6koRjZfk7wibfzgEna/QrGUWOhhkxz1MkSv3rG2j/s=    

#Adding stage host to /etc/hosts
before_install:
  - sudo sh -c 'echo "\n\n${STAGE_IP} ${STAGE_HOST}" >> /etc/hosts'
  - cat /etc/hosts
  - sudo apt-get install mailutils

#Skipping install phase
install: true

#Caching Maven and Sonar work directory to speed up the build
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"

#Activating sonarqube addon (Cf. script phase)
addons:
  sonarqube: true

#Defining how to build. For stage environment, we want to make a quality check also
script:
  - mvn -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey="clickP_${TRAVIS_BRANCH}" -DTOMCAT_MANAGER_LOGIN=${TOMCAT_MANAGER_LOGIN} -DTOMCAT_MANAGER_PASSWORD=${TOMCAT_MANAGER_PASSWORD} 

# We are on the staging branch, so we deploy the application automatically after a successfull build
after_success:
  - mvn tomcat7:redeploy || mvn tomcat7:deploy
  - curl http://clickp.stage.env:8080/clickcount/rest/healthcheck
  - echo "test" | mailx -s "test" gregoire.beaudequin@gmail.com  
