language: java
jdk:
  - oraclejdk8

before_install: sudo sh -c 'echo "ickp.stage.env 88.171.128.121" >> /etc/hosts'

install: true

script : mvn clean package

cache:
  directories:
   - $HOME/.m2

#Adress must be resolvable by DNS
addons:
  hosts:
  - clickp.stage.env 88.171.128.121

git:
  depth: 3

after_success:
  - if [[ $TRAVIS_BRANCH == "staging" ]]; then mvn tomcat7:redeploy || mvn tomcat7:deploy; fi

#default notification OK
notifications:
  email:
    on_success: never
    on_failure: never

