language: java
jdk:
- oraclejdk8
before_install: sudo sh -c 'echo "ickp.stage.env 88.171.128.121" >> /etc/hosts'
install: true
script: 
  #- mvn clean package
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN
cache
  directories:
  - "$HOME/.m2"
addons:
  hosts:
  - clickp.stage.env 88.171.128.121
  sonarqube: true
git:
  depth: 3
after_success:
- if [[ $TRAVIS_BRANCH == "staging" ]]; then mvn tomcat7:redeploy || mvn tomcat7:deploy;
  fi
notifications:
  email:
    on_success: never
    on_failure: never

Defining sonarQubeToken
env:
  global:
    secure: ppgQNWzQYpBvKias80ZcdDaXyhuXSc/va5Nz7D10wOWKfNuVsbFGx/dzaXcIdoJSqdoExCZMRqUhmMc1reAWu02JSSIvNvpKTCP1w+BHztEAF7nOUdjFBebU9M1Zd0YUAkLTC7QnfekEGeeUvg5oPS569K7mYJoAIykW3XFiBcLYZy+9bxBe9pM3sUC0KeGYJ2UwEB4gDM+/wnanz8JAJvumLw1NS729FxgmJ7sZIgytS3a1ARsAZrLX8gdHGDZiY62H6h6bifnWCuFUcqTGjzTBq1iq8zB3KCIWLZEsDG6hyPZWjXGsSs+Dhs/WqW/yQgSHjIEKUYxhY9inLfo4F6M0T4wD2IDOTk6Krb3wxGdmcWOVylItXIakaABwaXOcEnj+3Dhq/yo9C1gnmJNsjqHUkenqSnw4insyuF9ZWiLvpCUJDFni+Hut/z661mAMLZycO2Au0zB49UG9mJAAyB5Fv4yAYuU5uKunBP89H+hD+RKutU8rXT5WAvAXc0CbKa2RLGwXoLO/UKECGk8akbAyJZZx0C3nyNg1qyoG6eZa940R5p6S9fv8dmRXRFAXBWUCJ0DOBsPL4ynFbmtLhSxSAjSH+0rFQ/P5K/545wqrdyYv5f5siRpwD86fFa00n7rJVHDqkGs3+l0xZM1hV8lGcu855paZbo8OvoNCUeU=
