language: java
jdk:
  - oraclejdk8
#install:
script : mvn clean package 

cache:
  directories:
   - $HOME/.m2

addons:
  hosts:
  - clickp.stage.env 88.171.128.121 

after_success:
  - mvn tomcat7:redeploy || mvn tomcat7:deploy

